"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import Head from "next/head";
import { MyProvider } from "./context";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Zehra Ecer",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <Head>
        <title>Zehra Ecer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
          integrity="sha384-GLhlTQ9K1j5aF4ZRR+I7D5xx5sVsOg6/8p6cJvZdT6uVb5eGG7zIswD8G6fX3dGf"
          crossOrigin="anonymous"
        />
        <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"
          integrity="sha384-lZN37fXk8pO2D6UFWfZ2Nz1FzAeM6mOH4+GOrOnBuT3zS5a9r5FIFkFD1g4lm2/Z"
          crossOrigin="anonymous"
          async
        ></script>
      </Head>
      <body className={inter.className}>
        <MyProvider>
          <div style={{ display: "flex", flexDirection: "column", justifyContent: "space-between", height: "100vh" }}>
            <div >
              <Header />
            </div>
            <div>
              {children}
            </div>
            <div>
              <Footer />
            </div>
          </div>
        </MyProvider>
      </body>
    </html>
  );
}
